#pragma once

// From glfw3.h
#define IRID_MOUSE_BUTTON_1         0
#define IRID_MOUSE_BUTTON_2         1
#define IRID_MOUSE_BUTTON_3         2
#define IRID_MOUSE_BUTTON_4         3
#define IRID_MOUSE_BUTTON_5         4
#define IRID_MOUSE_BUTTON_6         5
#define IRID_MOUSE_BUTTON_7         6
#define IRID_MOUSE_BUTTON_8         7
#define IRID_MOUSE_BUTTON_LAST      IRID_MOUSE_BUTTON_8
#define IRID_MOUSE_BUTTON_LEFT      IRID_MOUSE_BUTTON_1
#define IRID_MOUSE_BUTTON_RIGHT     IRID_MOUSE_BUTTON_2
#define IRID_MOUSE_BUTTON_MIDDLE    IRID_MOUSE_BUTTON_3 
