# Determine target architecture
if ((CMAKE_SYSTEM_PROCESSOR MATCHES "AMD64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "x86") AND CMAKE_SIZEOF_VOID_P EQUAL 8)
	set(TARGET_ARCHITECTURE_X64 1)
	set(TARGET_ARCHITECTURE_NAME "x86-64")
elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "AMD64" AND CMAKE_SIZEOF_VOID_P EQUAL 4)
	set(TARGET_ARCHITECTURE_X86 1)
	set(TARGET_ARCHITECTURE_NAME "x86")
endif()